### ISSUE TITLE
PyTree compatibility & General Qs

### ISSUE THREAD

**Issue by LouisDesdoigts** [dfm/jpu#3]
Hey DFM, firstly I want to say thanks because this is something I have wanted to build myself for a long time! I wanted to ask a few things about the software since this would be incredibly useful for my research. 

> it isn't currently compatible with Pytree objects

Most of my software is built heavily on Jax pytrees so I was hoping for some clarity on why this is the case. From looking at the code base its primarily wrappers around the `jax.numpy` functions, which as I understand should integrate fine with pytrees. I did some testing using some jax-pytree classes (equinox and pytreeclass) and was able to integrate jpu fine, applying various jax transformations and the functions from the `jax.scipy` module:

```python
import jax
import jax.numpy as np
from functools import partial
from jpu import UnitRegistry, numpy as jnpu
import pytreeclass as pytc

u = UnitRegistry()

def get_class(type):
    if type == 'pytc':
        module = pytc.TreeClass
    elif type == 'eqx':
        module = eqx.Module

    class Rectangle(module):
        length: float
        width: float

        def __init__(self, length, width):
            self.length = float(length) * u.m
            self.width = float(width) * u.m

        def __call__(self):
            return (self.length * self.width).to('cm^2').magnitude
    
    return Rectangle

pytree_rect = get_class('pytc')(1, 2)
eqx_rect = get_class('eqx')(1, 2)

@jax.jit
@partial(jax.vmap, in_axes=(None, 0))
@jax.grad
def vmap_loss(pytree, y):
    return jax.scipy.stats.norm.logpdf(y, pytree())

ys = 10**np.arange(4, 7)
vmap_loss(pytree_rect, ys), vmap_loss(eqx_rect, ys)

loss(pytree_rect), loss(eqx_rect)

>>>(Rectangle(
>>>   length=<Quantity([-2.00e+08  1.60e+09  1.96e+10], 'meter')>, 
>>>   width=<Quantity([-1.0e+08  8.0e+08  9.8e+09], 'meter')>
>>> ),
>>> Rectangle(
>>>   length=<Quantity([-2.00e+08  1.60e+09  1.96e+10], 'meter')>,
>>>   width=<Quantity([-1.0e+08  8.0e+08  9.8e+09], 'meter')>
>>> ))
```

I'm curious as to why jpu isn't compatible as this seems to work fine for me, or what exactly are the limitations in this case? 

I'd be very interested in helping develop this software, let me know what the general issues are and I may be able to help!

**Comment by dfm** [comment]
The "it" in the quote there is actually the `__jax_array__` interface (you can't have a Pytree object that also implements `__jax_array__`, although I forget the exact failure modes), but as you've seen, `jpu` works just fine with Pytrees :D

**Comment by dfm** [comment]
Also: Any help would be appreciated! I don't know of specific issues, but I'd be keen to collaborate on any problems you find or features you want!
